#!/usr/bin/env python3
"""
Compresses 64x64 (or any WxH) 1-bit animation frames using PackBits-style
RLE. Kept here for reference / future animation updates — the animation
currently embedded in display_ui.cpp was already compressed this way.

Usage:
    1. Save a raw frame array (the block starting with
       `const byte PROGMEM frames[][N] = {` and ending with `};`) into a
       file named raw_frames.h in this same folder.
    2. Run: python compress_frames.py
    3. It prints the size savings and writes animation_data.h.
"""

import re
import sys

INPUT_FILE = "raw_frames.h"
OUTPUT_FILE = "animation_data.h"


def parse_frames(text):
    frame_blocks = re.findall(r"\{([^{}]*)\}", text)
    frames = []
    for block in frame_blocks:
        nums = [int(x.strip(), 0) for x in block.split(",") if x.strip() != ""]
        if nums:
            frames.append(bytes(nums))
    return frames


def packbits_encode(data: bytes) -> bytes:
    """
    header < 128:  (header + 1) literal bytes follow, copy verbatim
    header >= 128: (257 - header) repeats of the single byte that follows
    """
    out = bytearray()
    i = 0
    n = len(data)
    while i < n:
        run_len = 1
        while i + run_len < n and data[i + run_len] == data[i] and run_len < 128:
            run_len += 1

        if run_len >= 2:
            header = 256 - (run_len - 1)
            out.append(header)
            out.append(data[i])
            i += run_len
        else:
            lit_start = i
            i += 1
            while i < n:
                if i + 1 < n and data[i] == data[i + 1]:
                    break
                if i - lit_start >= 128:
                    break
                i += 1
            lit_len = i - lit_start
            out.append(lit_len - 1)
            out.extend(data[lit_start:i])
    return bytes(out)


def main():
    try:
        with open(INPUT_FILE) as f:
            text = f.read()
    except FileNotFoundError:
        print(f"Couldn't find {INPUT_FILE}. See the instructions at the top of this script.")
        sys.exit(1)

    frames = parse_frames(text)
    if not frames:
        print("No frames found in raw_frames.h — check the format.")
        sys.exit(1)

    frame_size = len(frames[0])
    print(f"Found {len(frames)} frames of {frame_size} bytes each.")

    compressed = [packbits_encode(f) for f in frames]
    raw_total = sum(len(f) for f in frames)
    comp_total = sum(len(f) for f in compressed)
    print(f"Raw size:        {raw_total} bytes")
    print(f"Compressed size: {comp_total} bytes ({100 * comp_total / raw_total:.1f}% of original)")

    offsets, lengths = [], []
    running = 0
    for cf in compressed:
        offsets.append(running)
        lengths.append(len(cf))
        running += len(cf)

    all_bytes = b"".join(compressed)

    with open(OUTPUT_FILE, "w") as f:
        f.write("#pragma once\n#include <Arduino.h>\n\n")
        f.write(f"// 1-bit animation, PackBits-compressed, {frame_size} bytes/frame raw.\n")
        f.write(f"// Generated by compress_frames.py from {len(frames)} source frames.\n")
        f.write(f"// Raw size would have been {raw_total} bytes; compressed to {comp_total} bytes.\n\n")
        f.write(f"#define FRAME_COUNT {len(frames)}\n\n")

        f.write(f"const uint16_t PROGMEM frame_offsets[FRAME_COUNT] = {{{', '.join(str(o) for o in offsets)}}};\n")
        f.write(f"const uint16_t PROGMEM frame_lengths[FRAME_COUNT] = {{{', '.join(str(l) for l in lengths)}}};\n\n")

        f.write(f"const uint8_t PROGMEM frame_data[{len(all_bytes)}] = {{\n")
        for i in range(0, len(all_bytes), 20):
            chunk = all_bytes[i:i + 20]
            f.write("  " + ", ".join(str(b) for b in chunk) + ",\n")
        f.write("};\n")

    print(f"Wrote {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
